"""create canonical safety persistence schema

Revision ID: 71efd8f68bbf
Revises: 
Create Date: 2026-09-15 05:52:14.437583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71efd8f68bbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('app_users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('HSE_VIEWER', 'HSE_ANALYST', 'HSE_OFFICER', 'ADMINISTRATOR', 'SYSTEM_AUDITOR', 'ML_OPS_ENGINEER')", name='chk_app_user_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('license_or_nda_ref', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("source_type IN ('SYNTHETIC', 'PUBLIC', 'AUTHORIZED_OIL')", name='chk_data_source_type'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('hse_prioritizations',
    sa.Column('priority_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('prioritization_basis', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=50), server_default=sa.text("'UNREVIEWED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("urgency_level IN ('IMMEDIATE_ACTION', 'SCHEDULED_AUDIT', 'ROUTINE_LOG')", name='chk_prioritization_urgency_level'),
    sa.PrimaryKeyConstraint('priority_id')
    )
    op.create_table('lsr_reference_catalogs',
    sa.Column('lsr_id', sa.String(length=50), nullable=False),
    sa.Column('rule_number', sa.Integer(), nullable=False),
    sa.Column('rule_title', sa.String(length=100), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('canonical_definition', sa.Text(), nullable=False),
    sa.Column('active_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('lsr_id')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('semantic_version', sa.String(length=50), nullable=False),
    sa.Column('model_architecture', sa.String(length=100), nullable=False),
    sa.Column('training_dataset_ref', sa.String(length=255), nullable=True),
    sa.Column('release_state', sa.String(length=50), server_default=sa.text("'ACTIVE_PRODUCTION'"), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('recurring_patterns',
    sa.Column('pattern_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('pattern_title', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('primary_activity', sa.String(length=100), nullable=False),
    sa.Column('primary_hazard', sa.String(length=100), nullable=False),
    sa.Column('primary_barrier_break', sa.String(length=100), nullable=False),
    sa.Column('affected_facility_id', sa.String(length=100), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('sif_potential_count', sa.Integer(), nullable=False),
    sa.Column('severity_tier', sa.String(length=20), nullable=False),
    sa.Column('first_observed_date', sa.Date(), nullable=False),
    sa.Column('latest_observed_date', sa.Date(), nullable=False),
    sa.Column('pattern_status', sa.String(length=50), server_default=sa.text("'ACTIVE_HOTSPOT'"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("pattern_status IN ('ACTIVE_HOTSPOT', 'INVESTIGATING', 'RESOLVED', 'ARCHIVED')", name='chk_pattern_status'),
    sa.CheckConstraint("severity_tier IN ('TIER_1_CRITICAL', 'TIER_2_HIGH', 'TIER_3_MONITORED')", name='chk_pattern_severity_tier'),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_table('rule_versions',
    sa.Column('rule_version_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ruleset_name', sa.String(length=100), nullable=False),
    sa.Column('ruleset_semantic_ver', sa.String(length=50), nullable=False),
    sa.Column('ruleset_sha256', sa.String(length=64), nullable=False),
    sa.Column('ruleset_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rule_version_id')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('payload_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_ip_address', sa.String(length=45), nullable=True),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('sequence_number')
    )
    op.create_index('idx_audit_seq', 'audit_events', ['sequence_number'], unique=False)
    op.create_table('safety_reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_report_id', sa.String(length=100), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('facility_id', sa.String(length=100), nullable=False),
    sa.Column('specific_location', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('raw_narrative', sa.Text(), nullable=False),
    sa.Column('normalized_narrative', sa.Text(), nullable=False),
    sa.Column('actual_outcome_severity', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('duplicate_cluster_id', sa.UUID(), nullable=True),
    sa.Column('narrative_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("processing_status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'PROCESSING_FAILED', 'REVIEWED')", name='chk_processing_status'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_duplicate', 'safety_reports', ['duplicate_cluster_id'], unique=False, postgresql_where=sa.text('duplicate_cluster_id IS NOT NULL'))
    op.create_index('idx_reports_facility_date', 'safety_reports', ['facility_id', sa.literal_column('event_date DESC')], unique=False)
    op.create_index('idx_reports_status', 'safety_reports', ['processing_status'], unique=False)
    op.create_table('evidence_spans',
    sa.Column('evidence_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('verbatim_text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('reasoning_justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('idx_evidence_target', 'evidence_spans', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('review_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('review_action', sa.String(length=50), nullable=False),
    sa.Column('original_sif_result', sa.String(length=20), nullable=False),
    sa.Column('revised_sif_result', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=False),
    sa.Column('corrections_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("review_action IN ('CONFIRM', 'CORRECT', 'REJECT', 'MARK_INSUFFICIENT_EVIDENCE', 'REQUEST_REANALYSIS')", name='chk_human_review_action'),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('pattern_memberships',
    sa.Column('membership_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('contribution_weight', sa.Numeric(precision=4, scale=3), server_default=sa.text('1.000'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['recurring_patterns.pattern_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id'),
    sa.UniqueConstraint('pattern_id', 'report_id', name='uq_pattern_report')
    )
    op.create_index('idx_pattern_memberships_pattern', 'pattern_memberships', ['pattern_id'], unique=False)
    op.create_index('idx_pattern_memberships_report', 'pattern_memberships', ['report_id'], unique=False)
    op.create_table('processing_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("execution_status IN ('SUCCESS', 'FAILED', 'TIMED_OUT')", name='chk_processing_run_status'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('barrier_findings',
    sa.Column('barrier_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('barrier_name', sa.String(length=100), nullable=False),
    sa.Column('barrier_category', sa.String(length=50), nullable=False),
    sa.Column('barrier_status', sa.String(length=50), nullable=False),
    sa.Column('is_critical_barrier', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("barrier_status IN ('PRESENT_VERIFIED', 'INCOMPLETE', 'MISSING', 'FAILED', 'BYPASSED', 'UNKNOWN')", name='chk_barrier_status_six_state'),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('barrier_id')
    )
    op.create_index('idx_barriers_critical', 'barrier_findings', ['barrier_name', 'barrier_status'], unique=False, postgresql_where=sa.text('is_critical_barrier = TRUE'))
    op.create_index('idx_barriers_report_status', 'barrier_findings', ['report_id', 'barrier_status'], unique=False)
    op.create_table('lsr_mappings',
    sa.Column('mapping_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('lsr_rule_code', sa.String(length=50), nullable=False),
    sa.Column('lsr_rule_name', sa.String(length=100), nullable=False),
    sa.Column('mapping_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('mapping_mechanism', sa.String(length=50), nullable=False),
    sa.Column('is_primary_rule', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index('idx_lsr_code', 'lsr_mappings', ['lsr_rule_code', 'report_id'], unique=False)
    op.create_table('safety_entities',
    sa.Column('entity_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('entity_class', sa.String(length=50), nullable=False),
    sa.Column('verbatim_text', sa.String(length=255), nullable=False),
    sa.Column('start_char_offset', sa.Integer(), nullable=False),
    sa.Column('end_char_offset', sa.Integer(), nullable=False),
    sa.Column('normalized_concept', sa.String(length=100), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('safety_signals',
    sa.Column('signal_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('signal_category', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('raw_text_mention', sa.String(length=255), nullable=True),
    sa.Column('signal_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_critical_precursor', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('sif_assessments',
    sa.Column('assessment_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sif_potential', sa.String(length=20), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('assessment_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('causal_rule_code', sa.String(length=100), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('is_active_assessment', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("sif_potential IN ('YES', 'NO', 'REVIEW')", name='chk_sif_potential_canonical'),
    sa.CheckConstraint("priority_level IN ('P1_CRITICAL', 'P2_HIGH', 'P3_STANDARD')", name='chk_sif_priority_level'),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index('idx_sif_active', 'sif_assessments', ['report_id', 'sif_potential', 'priority_level'], unique=False, postgresql_where=sa.text('is_active_assessment = TRUE'))
    op.create_table('safety_relations',
    sa.Column('relation_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_verb', sa.String(length=100), nullable=False),
    sa.Column('object_entity_id', sa.UUID(), nullable=False),
    sa.Column('temporal_preposition', sa.String(length=50), nullable=True),
    sa.Column('is_negated', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['safety_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['safety_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_relations')
    op.drop_index('idx_sif_active', table_name='sif_assessments', postgresql_where=sa.text('is_active_assessment = TRUE'))
    op.drop_table('sif_assessments')
    op.drop_table('safety_signals')
    op.drop_table('safety_entities')
    op.drop_index('idx_lsr_code', table_name='lsr_mappings')
    op.drop_table('lsr_mappings')
    op.drop_index('idx_barriers_report_status', table_name='barrier_findings')
    op.drop_index('idx_barriers_critical', table_name='barrier_findings', postgresql_where=sa.text('is_critical_barrier = TRUE'))
    op.drop_table('barrier_findings')
    op.drop_table('processing_runs')
    op.drop_index('idx_pattern_memberships_report', table_name='pattern_memberships')
    op.drop_index('idx_pattern_memberships_pattern', table_name='pattern_memberships')
    op.drop_table('pattern_memberships')
    op.drop_table('human_reviews')
    op.drop_index('idx_evidence_target', table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index('idx_reports_status', table_name='safety_reports')
    op.drop_index('idx_reports_facility_date', table_name='safety_reports')
    op.drop_index('idx_reports_duplicate', table_name='safety_reports', postgresql_where=sa.text('duplicate_cluster_id IS NOT NULL'))
    op.drop_table('safety_reports')
    op.drop_index('idx_audit_seq', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('rule_versions')
    op.drop_table('recurring_patterns')
    op.drop_table('model_versions')
    op.drop_table('lsr_reference_catalogs')
    op.drop_table('hse_prioritizations')
    op.drop_table('data_sources')
    op.drop_table('app_users')
    # ### end Alembic commands ###
